sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 660906asd
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx9420dc674889a827
    secret: 9a0eb275ad0443dca990ed8d20bd06fd
    notify-url: https://58869fb.r2.cpolar.top/notify/paySuccess
    refund-notify-url: https://58869fb.r2.cpolar.top/notify/refundSuccess